### ISSUE TITLE
Search using non-UTC days

### ISSUE THREAD

**Issue by kevinburke** [saintpete/logrole#6]
Currently all DateCreated><= searches are implemented with the date field in UTC. This can be confusing for a user that has a different timezone set - if they are UTC-8, they might not see the 8 hours of results that are from the previous day. 

To fix this Twilio would either need to offer a TZ-aware search option, allow hours-based searching, or we'd need to search multiple days and filter the result sets in memory.

**Comment by cyoilya** [comment]
@kevinburke Why not convert UTC to the timezone in the user's settings and then running the search?  I.e. start date of 00:00:00 EDT on 11/04/16 ==> 04:00:00 UTC on 11/04/16 and end date of 23:59:59 EDT on 11/04/16 ==> 03:59:59 UTC on 11/05/16. 

We use a Carbon library in PHP to do the timezone calculations offsets for us (makes it trivial) and then doing the filter by the new date/time in UTC.

**Comment by kevinburke** [comment]
If I'm reading correctly that's basically this: "we'd need to search multiple days and filter the result sets in memory." For your example, we would need to send `StartDate<=2016-11-05&StartDate>=2016-11-04` and then filter out the results that aren't in the available time range. Twilio doesn't offer more granular date filters. 

The other problem is since we're filtering on the server a "page" of results may have less than 50 results. For example, Twilio returns results in date order and lets you page backwards, so you'd start getting results for 23:59:59 on 11/05/16 and going backwards from there. We'd filter out those results since they don't match the time range, which would require another API query, and continually querying until we finally got records in the right time range.

**Comment by cyoilya** [comment]
That's correct, Kevin.  We do need a solution for Eastern standard time because after this weekend, we'll be able to only get recording up to 6:59 PM because of -5 hour difference (right now, it's at -4 hours from UTC).  

We do care about the ending time, not so much for the beginning time, if it simplifies the logic somewhat.  In other words, it's OK to use UTC 00:00:00 on the previous day instead of UTC 04:00:00 (or 05:00:00 after this weekend's daylight savings time switch) so no need to adjust that logic.  However, on the ending time, it has to go up to 11:59 PM EDT on 11/04 and not stop at 7:59/6:59 PM.  

What is the solution here?

Thanks.

**Comment by kevinburke** [comment]
We'd need to convert the date range to UTC, search that range of days, then filter the results.

The "max resource age" filters work at a lower level - there's no limitation against searching Twilio for older results, they just won't be viewable in the final display.

**Comment by kevinburke** [comment]
So the part I was missing is that the Dashboard supports much finer-grained search. I'm implementing this in twilio-go now. I think we can get to a really good place.

**Comment by kevinburke** [comment]
I've just merged the fix for this. Upgrade to 0.71 or higher to get a version that has timezone-aware, to-the-hour search.
